(ns prot-mass.core
  (:require [clojure.string :as s]))

(def input (slurp "/opt/apps/rosalind/masstable.txt"))

;; read the file and convert it to a hash-map
(def table
  (into {} (map vec (for [[a b]
                          (partition 2 (filter #(> (count %) 0) (s/split input #" |\n")))]
                      (cons (keyword a) [(read-string b)])))))

(reduce
 (fn [y x] (+ y (table (keyword (str x))))) 0
        (seq "LWDIGRMNASLGIQNNLNIRPTAHNHKFNKRPDKGKAPSHFWSGFCFWEFSDIHFKSLSWMLCDYDNQFKFDDAIQCPQHGCQKYIHPWPKNQFCTWLGSKTNMNWHENHLRWHDVICTDCFRMLNAGGFHGSYEEMVHREKQNHDNWKDGCPSCGIAILCWYQHQYWSLAVSSAEFGTNHYQRHGEGHERFPLVPLLVQWVHSVHSVKVTNVMPTLMANWAPWTLVPLPPATVFGQCIEILTGCCLMFDSLTGLSAYFKCFPVAKFFGAWWMIDPENFGQDVPEGVGERAQKVRKAHEKWSTDKDFKFLRVCEYGPCNFIFIECRVLSPNQFGEQNLRMNQEGYHFLNCRLRKRCLKLIDRSSCQATANANTLLWEQQYFHVYASPKHWSSRATNIQSQENPTPVDMLFHCSIKHRPGLCGGFNGLVGNKEIPADFQSNAIKSWMGWWMLPTDRDQGSNHIQTCTGLIFFFRLWTFLEMVFPYNVTLRLVHQHPLTIYCCFGINFVYIRHLSNILDIAPCLMKTQGHGSDWPFIFILNSTSAQNFRIHGQCTFVMYGGITTCCQDDNRINKDRTMANWDNKSMKVVNGHDQTKAHHPGNMMSYRCEEENGYWRHELDYQCWVWFIFGMAGEIAIQDDWYLDWFDTHNESHGAFYLWKPRFWYKWKTDYCQCTMPKHDYALVWIWRASNSMFNVWEGNTRFIHRKWQVPNMLYEAKWQACATKPRYAFSGHLSIFKSTYCWLSNWLFFWENTWLPGIYAGPNPWYKTELFWPAYHKNFLAYRPILRMSTRHQTNGVFPDWCPHRYLYDPQS"))





